### ISSUE TITLE
Track Maven version in Jenkins tools from the VM templates

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/jenkins-infra#2100]
https://github.com/jenkins-infra/jenkins-infra/pull/2096 uses the updatecli manifest at https://github.com/jenkins-infra/jenkins-infra/blob/production/updatecli/weekly.d/buildmaster-tools-maven.yaml

It checks for the Maven available versions on the internet.

We might want to check which version is defined for the "current" VM template instead (the VM version for azure template in hieradata/common.yml is the same as the latest packer_image release)

**Comment by lemeurherve** [comment]
Fixed by https://github.com/jenkins-infra/jenkins-infra/pull/2220
