### ISSUE TITLE
Installing Jenkins from pkg.jenkins.io via APT is failing due to https -> http redirect

### ISSUE THREAD

**Issue by tianon** [jenkins-infra/jenkins-infra#2191]
See https://stackoverflow.com/q/72412100/433558 for a concrete instance.

The short version is that folllowing the instructions from https://pkg.jenkins.io/debian/ verbatim now fails with something like this:

```console
Err:28 https://pkg.jenkins.io/debian binary/ jenkins 2.349
  Redirection from https to 'http://mirrors.jenkins.io/debian/jenkins_2.349_all.deb' is forbidden [IP: 151.101.2.133 443]
```

I believe the underlying cause is https://www.jenkins.io/blog/2022/05/13/mirrors/, and I believe the fix is probably updating to `https` in the following line? (and maybe any/all other references to `mirrors.jenkins.io`?)

https://github.com/jenkins-infra/jenkins-infra/blob/df1a23b54bce3328f7466dc4fb4623a1173925ab/dist/profile/templates/pkgrepo/debian_htaccess.erb#L16

**Edit:** ah, https://github.com/jenkins-infra/helpdesk/issues/2957#issuecomment-1140098592 :see_no_evil: :heart:

**Comment by dduportal** [comment]
Many thanks @tianon . Your fixed helped a lot: we had a unexpected "2-years old" configuration applied which led to the old domain in HTTP no redirecting to HTTPS as expected.

But with your PR, no worries to have on the underlying redirect vhost or not: full HTTPS ahead !

**Comment by tianon** [comment]
My pleasure!  I'm glad I found the right repository to make a PR to :smile:
