### ISSUE TITLE
updatecli: add a condition on AMI images existence

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/jenkins-infra#2219]
> The tag build on packer hasn't finished yet, that explains why these values are empty.

_Originally posted by @lemeurherve in https://github.com/jenkins-infra/jenkins-infra/pull/2218#discussion_r900057021_

**Comment by dduportal** [comment]
Closing as we do not use EC2 anymore since https://github.com/jenkins-infra/jenkins-infra/pull/2929
