### ISSUE TITLE
Add a condition on packer-image template to check all versions are available

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/jenkins-infra#2410]
To avoid error like the release of Jenkins docker image on trusted.ci.jenkins.io because the win2019 azure-arm step failed.

https://trusted.ci.jenkins.io:1443/log/Azure%20VM%20Agent%20(Auto)/
> AzureVMCloudVerificationTask: verify: win-2019 could not be verified:
> Status code 404, "{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Compute/galleries/prod_packer_images/images/jenkins-agent-windows-2019/versions/0.43.0' under resource group 'prod-packer-images' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}"

**Comment by sonali-rajput** [comment]
Can you please further give more details about the issue?

**Comment by dduportal** [comment]
> Can you please further give more details about the issue?

We are sorry @sonali-rajput but this issue is not really a newcomer issue. It was written as a reminder for the Jenkins infra team. 

You might want to search for beginners issues on the jenkinsci organization instead, to avoid this kind of blocker.

**Comment by sonali-rajput** [comment]
> > Can you please further give more details about the issue?
> 
> We are sorry @sonali-rajput but this issue is not really a newcomer issue. It was written as a reminder for the Jenkins infra team.
> 
> You might want to search for beginners issues on the jenkinsci organization instead, to avoid this kind of blocker.

Alright, Thanks for letting me know.

**Comment by dduportal** [comment]
Done with https://github.com/jenkins-infra/jenkins-infra/blob/6deb6c7667aadec81671e3e36623bcd1e2bb18e2/updatecli/weekly.d/jenkinscontroller-agents-packer-agent-all-in-one.yaml#L45-L51
