### ISSUE TITLE
Acceptance Test Harness - install Ant for the tests

### ISSUE THREAD

**Issue by ampuscas** [jenkins-infra/jenkins-infra#2690]
There are some tests which need to have Ant installed in order to run, otherwise they are skipped. We should have Ant installed locally on some nodes so these tests can run.
Examples of tests that need Ant installed can be found on this PR https://github.com/jenkinsci/acceptance-test-harness/pull/1066/files and the result of test runs: https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/PR-1066/1/testReport/plugins/AntPluginTest/

**Comment by lemeurherve** [comment]
Hello @ampuscas, are there any constraint about its version or could we install the last one (currently 1.10.13) and keep it updated, and which OS are concerned?

**Comment by lemeurherve** [comment]
Discussing it a bit more, as the test runs [inside the ath docker container](https://github.com/jenkinsci/acceptance-test-harness/blob/master/Jenkinsfile#L57), there is no need for `ant` to be installed on the agent as it can be installed directly in this container instead.
