### ISSUE TITLE
Split `jenkinscontroller-agents` updatecli manifest so each PR would have an appropriate title

### ISSUE THREAD

**Issue by hervelemeur** [jenkins-infra/jenkins-infra#3071]
> splitting this manifest https://github.com/jenkins-infra/jenkins-infra/blob/production/updatecli/weekly.d/jenkinscontroller-agents.yaml in several parts so each updatecli PR would have an appropriate title

_Originally posted by @lemeurherve in https://github.com/jenkins-infra/jenkins-infra/issues/3066#issuecomment-1721066281_

**Comment by dduportal** [comment]
Do you think we can tag this issue as a first good issue?

**Comment by hervelemeur** [comment]
I wanted to but couldn't from this (phone) account, go for it!

**Comment by shubhamch71** [comment]
@hervelemeur @lemeurherve  @dduportal  Hello , I am interested in this issue and I would like to contribute to this issue. Can you please assign it to me !!!

**Comment by dduportal** [comment]
> @hervelemeur @lemeurherve @dduportal Hello , I am interested in this issue and I would like to contribute to this issue. Can you please assign it to me !!!

you can start working on it: please send a PR :)

**Comment by shubhamch71** [comment]
@dduportal  okay got it !! thanks !!

**Comment by shubhamch71** [comment]
@dduportal @hervelemeur   I was thinking about  splitting the jenkinscontroller-agents.yaml file into the following three files:
1)Bump Windows VM agent disk size
2)Bump Azure VM image version
3)Bump container image versions

This would allow handling updates for each agent type independently in separate pull requests. 

Wanted to know if I can go ahead or please let me know if you want me to split it any other way !!

**Comment by dduportal** [comment]
> @dduportal @hervelemeur I was thinking about splitting the jenkinscontroller-agents.yaml file into the following three files: 1)Bump Windows VM agent disk size 2)Bump Azure VM image version 3)Bump container image versions
> 
> This would allow handling updates for each agent type independently in separate pull requests.
> 
> Wanted to know if I can go ahead or please let me know if you want me to split it any other way !!

That looks good, however we would be interested in grouping the Azure Image Gallery version with the "all in one" container because it is the same image built by jenkins-infra/packer-image (same release, same content).

That would mean the following split:

1) Bump Windows VM agent disk size
2) Bump packer agent templates (all-in-one) version 
3) Bump jnlp container agent image jenkins/inbound-agent (JDK17)
`

**Comment by shubhamch71** [comment]
@dduportal @hervelemeur I have split the files as you mentioned and created a pull request #3125 , please look into it and tell me if you need any changes !!!!

**Comment by dduportal** [comment]
https://github.com/jenkins-infra/jenkins-infra/pull/3125 was merged successfully
