### ISSUE TITLE
[profile::pkgrepo] mirror-scripts/batch-upload.bash script isn't working since a long time

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/jenkins-infra#3361]
### Reproduction steps

https://github.com/jenkins-infra/mirror-scripts/blob/main/batch-upload.bash is looping over containers of getjenkinsio storage account, but this storage account doesn't contain any container since a long time (I didn't managed to determine when exactly).

Does anyone remember what were the names of these containers by any chance?
They should correspond to folders of the "jenkins" one in /srv/release but I don't know which ones of them: https://github.com/jenkins-infra/mirror-scripts/blob/9bfccd785f2b6f901891b35a2d7b0603fd683274/batch-upload.bash#L16C39-L16C53

### Expected Results

A sync

### Actual Results

No sync

**Comment by dduportal** [comment]
cc @olblak @daniel-beck @timja does it ring a bell?

**Comment by dduportal** [comment]
Removed in https://github.com/jenkins-infra/mirror-scripts/pull/25
